using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
public class Ability : MonoBehaviour
{

    public Energy energy;
    public Sprite newSpriteMove;
    public Sprite newSpriteJump;
    public Sprite newSpriteReverse;
    public Sprite newSpritenomal;
    private Image image;

    float a;
    int b;

    // Use this for initialization
    void Start()
    {
        a = 3;
        b = 0;
        // SpriteRendererï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½Ü‚ï¿½
        image = GetComponent<Image>();
    }

    // Update is called once per frame
    void Update()
    {
        // 1 ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Alpha1))
        {
            // ï¿½æ‘œï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½Ü‚ï¿½
            a = 0;
        }
        // 2 ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Alpha2))
        {
            // ï¿½æ‘œï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½Ü‚ï¿½
            a = 1;
        }
        // 3 ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Alpha3))
        {
            // ï¿½æ‘œï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½Ü‚ï¿½
            a = 2;
        }
        // 4 ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Alpha4))
        {
            // ï¿½æ‘œï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½Ü‚ï¿½
            a = 3;
        }

       //ï¿½}ï¿½Eï¿½Xï¿½zï¿½Cï¿½[ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½Ê‚ð‘«‚ï¿½
        a += Input.mouseScrollDelta.y;
        
        b = (int )a % 4;
     
        if (b == 0)
        {
            energy.isMoveObjectSet = true;
            energy.isGravityIncreaseSet = false;
            energy.isGravityInversionSet = false;
            image.sprite = newSpriteMove;
        }
        if (b == 1)
        {
            energy.isMoveObjectSet = false;
            energy.isGravityIncreaseSet = true;
            energy.isGravityInversionSet = false;
            image.sprite = newSpriteJump; 

        }
        if (b == 2)
        {
            energy.isMoveObjectSet = false;
            energy.isGravityIncreaseSet = false;
            energy.isGravityInversionSet = true;
            image.sprite = newSpriteReverse;
        }
        if (b == 3)
        {
            energy.isMoveObjectSet = false;
            energy.isGravityIncreaseSet = false;
            energy.isGravityInversionSet = false;
            image.sprite = newSpritenomal;
        }

    }
}